// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vimdhqgjbwlesiacqudg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbWRocWdqYndsZXNpYWNxdWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzg3MDUsImV4cCI6MjA2ODY1NDcwNX0.B9cNspGa_sMJxNvI5Coqwtp9YCUSge4Ay-5p9WC08Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});